# Site settings
name: 千叶
email: albert.shen@foxmail.com
author: Albert Shen
url: https://github.com/albertShen12/
resume_site: https://github.com/albertShen12/
github: https://github.com/albertShen12/
baseurl: ""
description: 千叶的个人主页
meta_description: 莲开千叶，万古传奇
motto: It's our wits that make us men.
banner: 莲开千叶，万古传奇。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: albertShen12

# Build settings
markdown: kramdown

#baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

